name: Code Testing using Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      
    - name: Testing Codes
      run: |
        pip install nose2 coverage

    - name: Testing FizzBuzz
      run: |
        cd fizzbuzz
        nose2 -v --with-coverage
        cd ..
        
    - name: Testing SuperFizzBuzz
      run: |
        cd super_fizzbuzz
        nose2 -v --with-coverage
        cd ..

    - name: Testing number
      run: |
        cd number
        nose2 -v --with-coverage
        cd ..
        
    - name: Testing FunnyString
      run: |
        cd funnystring
        nose2 -v --with-coverage
        cd ..
        
    - name: Testing AlternatingChar
      run: |
        cd alternatingchar
        nose2 -v --with-coverage
        cd ..
        
    - name: Testing CaesarCipher
      run: |
        cd caesarcipher
        nose2 -v --with-coverage
        cd ..

    - name: Testing TwoChar
      run: |
        cd twochar
        nose2 -v --with-coverage
        cd ..
        
    - name: Testing GridChallenge
      run: |
        cd gridchallenge
        nose2 -v --with-coverage
        cd ..
